exclude:
- README.md
- LICENSE
- vendor

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-default-layout
- jekyll-include-cache
- jekyll-feed

encoding: utf-8
title: OpenUTD
lang: en-US

logo: "/assets/tux_logo.png"
favicon: "/assets/favicon.png"
repository: "openutd/openutd.github.io"

navigation_header:
  Home: /
  Contact: /contact.html
  Events: /events/
  Categories: /categories.html

navigation_footer:
  OpenUTD: /

paginate: 3
paginate_path: "/events/page:num"
future: true
collections:
  posts:
    title: Events
    output: true
